server:
  port: 8080
  servlet:
    context-path: /fake-suomifi-tunnistus
  ssl:
    enabled: false
management:
  endpoint:
    health:
      enabled: true
cas:
  monitor:
    endpoints:
      endpoint:
        health:
          access: PERMIT
