server:
  port: 8080
  servlet:
    context-path: /fake-suomifi-tunnistus
  ssl:
    enabled: false
  tomcat:
    portHeader:
    protocolHeader:
    remoteIpHeader:
  useForwardHeaders: false
management:
  endpoint:
    health:
      enabled: true
cas:
  authn:
    accept:
      users:
    samlIdp:
      entityId: ${cas.server.prefix}
      scope: ${cas.custom.properties.host}
  custom:
    properties:
      host: localhost:${server.port}
      scheme: http
      url-virkailija: http://localhost:${server.port}
      service-username: user
      service-password: pass
  httpWebRequest:
    header:
      xframe: false
      xss: false
      xcontent: false
      hsts: false
  monitor:
    endpoints:
      endpoint:
        health:
          access: PERMIT
  samlCore:
    securityManager: com.sun.org.apache.xerces.internal.util.SecurityManager
  server:
    name: ${cas.custom.properties.scheme}://${cas.custom.properties.host}
    prefix: ${cas.server.name}${server.servlet.context-path}
  tgc:
    path: ${server.servlet.context-path}
    secure: false
  warningCookie:
    path: ${server.servlet.context-path}
    secure: false
